<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>hanfire_forum_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Hangfire.Redis.StackExchange" Version="1.12.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HanfireForum.Data\HanfireForum.Data.csproj" />
    <ProjectReference Include="..\HangfireForum.Domain.Common\HangfireForum.Domain.Common.csproj" />
    <ProjectReference Include="..\HangfireForum.Services\HangfireForum.Services.csproj" />
  </ItemGroup>

</Project>
